#!/usr/bin/with-contenv bash

	screen -T xterm-256color -D -m -S rtorrent \
	s6-setuidgid abc rtorrent \
	-n -o import=/config/rtorrent/rtorrent.rc

until [ -e "/config/rtorrent/rtorrent_sess/rtorrent.lock" ];
do
sleep 1s
done

rtorrent_pid=$(< /config/rtorrent/rtorrent_sess/rtorrent.lock cut -d '+' -f 2)
tail -n 1 -f /config/log/rtorrent/rtorrent.log --pid "$rtorrent_pid"
