#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config{/log/rtorrent,/rtorrent/rtorrent_sess} \
	/downloads{/completed,/incoming,/watched}


# copy config
PREV_DIR=$(pwd)

[[ ! -e /config/rtorrent/rtorrent.rc ]] && \
	cp /defaults/rtorrent.rc /config/rtorrent/rtorrent.rc

# delete lock file if exists
[[ -e /config/rtorrent/rtorrent_sess/rtorrent.lock ]] && \
	rm /config/rtorrent/rtorrent_sess/rtorrent.lock

# permissions
chown abc:abc \
	/downloads \
	/downloads{/completed,/incoming,/watched}

chown -R abc:abc \
	/config \
	/run

chmod 644 /etc/logrotate.d/*
