#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config{/log/rtorrent,/rtorrent/session,/rtorrent/pyroscope/rtorrent.d} \
	/downloads \
	/watch

# copy config
[[ ! -e /config/rtorrent/rtorrent.rc ]] && \
	cp /defaults/rtorrent.rc /config/rtorrent/rtorrent.rc

cd /defaults/pyroscope
shopt -s globstar nullglob
for i in **
do
	[[ ! -e "/config/rtorrent/pyroscope/${i}" ]] && cp "${i}" "/config/rtorrent/pyroscope/${i}"
done

# delete lock file if exists
[[ -e /config/rtorrent/session/rtorrent.lock ]] && \
	rm /config/rtorrent/session/rtorrent.lock

# permissions
chown abc:abc \
	/run

chown -R abc:abc \
	/config \
	/downloads \
	/watch

chmod 644 /etc/logrotate.d/*
